name: sms
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  get: ^4.6.5
  flutter_sms_inbox: ^1.0.2
  flutter_svg: ^1.1.6
  shared_preferences: ^2.0.16
  new_gradient_app_bar: ^0.2.0
  flutter_share: ^2.0.0
  device_preview: ^1.1.0
  fluttercontactpicker: ^4.7.0
  clippy_flutter: ^1.1.1
  permission_handler: ^10.2.0


  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/
    - assets/logo/
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/fonts/


  fonts:
    - family: A Jannat LT Regular
      fonts:
        - asset: assets/fonts/AAJannatLT.ttf

  uses-material-design: true